[package]
name = "session-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goose = "0.17.2"
goose-eggs = "0.5.2"
tokio = "1.35.1"
